### ISSUE TITLE
[2014APAC][ja] code_of_conduct.html

### ISSUE THREAD

**Issue by whosaysni** [pycontw/APAC2014WebContent#13]

**Comment by ccwang002** [comment]
I'd like to give this page low priority since this page is formal and we'd want everyone to have the same understanding about our code of conduct, which now English version serves this purpose.

So I think if we have resources we will work on this, but it is fine if this page remains English.

**Comment by ccwang002** [comment]
Will be translated by Yahsuan Lee

**Comment by ccwang002** [comment]
Reopen
