### ISSUE TITLE
Frontpage content rewrite

### ISSUE THREAD

**Issue by ccwang002** [pycontw/APAC2014WebContent#24]
Actually frontpage content (`index.html`) is not in this repo, it is in the [web dev repo](https://bitbucket.org/pycontw/pycon-apac-2014/src) (`conweb/templates/index.html`). I put it here as a remainder that if anyone has time, one should try improve our frontpage.

Currently its content is same as the about page. Any ideas are welcomed : )

**Comment by keitheis** [comment]
It's really not that easy to write front page of a PyCon web site. So usually people fill it with blogs, news, or stuff:
- http://apac-2013.pycon.jp/
- http://kiwi.pycon.org/ <- two phrases maybe for us
- https://ep2014.europython.eu/en/ 
- https://us.pycon.org/2014/

@ccwang002  How about we just call for better two phrases? And ask @minipai about how look to beat kiwi.pycon.org or not too far from it? :tongue:

**Comment by ccwang002** [comment]
@keitheis I don't get the meaning "two phrases", could you explain a bit? anyway, I like the front page design of Kiwi PyCon.

**Comment by keitheis** [comment]
We ...
... first phrase.

Then ...
... second phrase.

^ That's it. Two phrases.

**Comment by uranusjr** [comment]
Is this still relevant? Mezzanine totally allows the front page to be editable, but an admin is required to fill in the content after the changes are made.

**Comment by keitheis** [comment]
@uranusjr yeah the whole main point is lacking of content. But since we have new plan that using blogs to replace the dummy content, I'll close this issue.
